yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('pk',)


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ('-created',)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'], name='unique_follow')
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        labels = {'text': 'Текст поста', 'group': 'Группа'}
        help_texts = {'text': 'Текст нового поста',
                      'group': 'Группа, к которой будет относиться пост'}
        fields = ['text', 'group', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        labels = {'text': 'Текст комментария'}
        help_texts = {'text': 'Текст нового комментария'}
        fields = ['text']

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def create_paginator(request, object):
    paginator = Paginator(object, settings.POSTS_ON_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    posts = Post.objects.all()
    page_obj = create_paginator(request, posts)
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = create_paginator(request, posts)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = create_paginator(request, posts)
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            user=request.user, author=author
        ).exists()
    else:
        following = False
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if not form.is_valid():
        context = {'form': form, 'is_edit': True}
        return render(request, 'posts/create_post.html', context)

    post = form.save(commit=False)
    post.author = request.user
    post.save()

    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    if not request.user == post.author:
        return redirect('posts:post_detail', post.id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if not form.is_valid():
        context = {'form': form, 'is_edit': False}
        return render(request, 'posts/create_post.html', context)

    form.save()

    return redirect('posts:post_detail', post.id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts_following = Post.objects.filter(author__following__user=request.user)
    page_obj = create_paginator(request, posts_following)
    context = {'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect(reverse('posts:profile', args=[username]))


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    posts_follower = Follow.objects.filter(user=user, author=author)
    if posts_follower.exists():
        posts_follower.delete()
    return redirect('posts:profile', username=author)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}
    Новый пост.
  {% else %}
    Редактировать пост
  {% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Новый пост.
            {% else %}
              Редактировать пост
            {% endif %}
          </div>
          <div class="card-body">
            {% load user_filters %}
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}

            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% for field in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text }}
                    </small>
                  {% endif %}
                </div>
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %}
  Подписки на авторов.
{% endblock %}
{% block content %}
  {% load thumbnail %}
  <div class="container py-5">
    <h1>Это страница подписок на авторов проекта Yatube.</h1>
    {% include 'posts/includes/paginator.html' %}
    <article>
      {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </article>
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Все записи в группе {{ group.title }}
{% endblock %}
{% block content %}
  {% load thumbnail %}
  <div class="container py-5">
    {% block header %}
      <h1>{{ group.title }}</h1>
    {% endblock %}
    <p>{{ group.description }}</p>
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </article>
    <a href="{% url 'posts:index' %}">На главную.</a>
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  Главная страница.
{% endblock %}
{% block content %}
  {% load thumbnail %}
  {% load cache %}
  <div class="container py-5">
    <h1>Это главная страница проекта Yatube.</h1>
    <h1>Последние обновления на сайте</h1>
    {% include 'posts/includes/paginator.html' %}
    <article>
      {% cache 20 index_page %}
        {% include 'posts/includes/switcher.html' %}
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      {% endcache %}
    </article>
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}.
{% endblock %}
{% block content %}
  {% load thumbnail %}
  <div class="container py-5">
    <article>
      <ul>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li>
            Группа: {{ post.group.slug }}<br>
          </li>
          <li>
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          </li>
        {% endif %}
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Всего постов автора:  <span >{{ post.author.posts.count }}</span>
        </li>
        <li>
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      {% if user == post.author %}
        <div class="col-md-6 offset-md-0">
          <a class="btn btn-primary"
            href="{% url 'posts:post_edit' post.id %}">Редактировать запись</a>
        </div>
      {% endif %}
      {% include 'posts/includes/comments.html' %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author.username }}.
{% endblock %}
{% block content %}
  {% load thumbnail %}
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.username }}.</h1>
      <h3>Всего постов: {{ author.posts.count }}</h3>
      {% if user != author %}
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
        {% endif %}
      {% endif %}
    </div>
    {% include 'posts/includes/paginator.html' %}
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text }}</p>
        {% if post.id %}
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a>
        {% endif %}<br>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </article>
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}